apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: workspace-charts
    namespace: dev
    files:
    # - vs
    # - rm-resource-catalog
    - template-hr-resource-guard.yaml
generatorOptions:
  disableNameSuffixHash: true
