apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  managedFields:
  - apiVersion: apiextensions.k8s.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:conversion:
          .: {}
          f:strategy: {}
        f:group: {}
        f:names:
          f:kind: {}
          f:listKind: {}
          f:plural: {}
          f:shortNames: {}
          f:singular: {}
        f:preserveUnknownFields: {}
        f:scope: {}
        f:version: {}
        f:versions: {}
      f:status:
        f:acceptedNames:
          f:kind: {}
          f:plural: {}
        f:conditions: {}
        f:storedVersions: {}
    manager: okhttp
    operation: Update
  name: buckets.epca.eo
spec:
  conversion:
    strategy: None
  group: epca.eo
  names:
    kind: Bucket
    listKind: BucketList
    plural: buckets
    shortNames:
    - bucket
    singular: bucket
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
