apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: harbor
      version: 1.7.3
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: common
  values:
    expose:
      ingress:
        annotations:
          kubernetes.io/tls-acme: 'true'
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/proxy-read-timeout: '600'

          # from chart:
          ingress.kubernetes.io/ssl-redirect: "true"
          ingress.kubernetes.io/proxy-body-size: "0"
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"

        hosts:
          core: harbor.myeox.at
          notary: harbor-notary.myeox.at

    persistence:
      persistentVolumeClaim: {}
        #registry:
        #  storageClass: aws-efs
        #chartmuseum:
        #  storageClass: aws-efs
        #jobservice:
        #  storageClass: aws-efs
        #database:
        #  storageClass: aws-efs
        #redis:
        #  storageClass: aws-efs
        #trivy:
        #  storageClass: aws-efs

    externalURL: https://harbor.myeox.at

    chartmuseum:
      enabled: false
    trivy:
      enabled: false
    notary:
      enabled: false

