apiVersion: v1
kind: ServiceAccount
metadata:
  name: workspace-api
  namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workspace-api
rules:
  - apiGroups: [""]
    verbs: ["get", "watch", "create"]
    resources:
      - secrets
  - apiGroups: [""]
    verbs: ["create", "get", "patch", "delete"]
    resources:
      - configmaps
      - persistentvolumeclaims
  - apiGroups: ["extensions"]
    verbs: ["get", "list"]
    resources:
      - ingresses
  - apiGroups: [""]
    verbs: ["create", "get", "delete"]
    resources:
      - namespaces
  - apiGroups: ["helm.toolkit.fluxcd.io"]
    verbs: ["create", "patch"]
    resources:
      - helmreleases
  - apiGroups: ["epca.eo"]
    verbs: ["create"]
    resources:
      - buckets
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: workspace-api
subjects:
  - kind: ServiceAccount
    name: workspace-api
    namespace: dev
roleRef:
  kind: ClusterRole
  name: workspace-api
  apiGroup: rbac.authorization.k8s.io
